---
version: '3'
services:
  bash:
    # image: micalexander/alpine-bash:latest
    build:
      context: ./alpine-bash
    hostname: alpine-bash
    container_name: bash
    environment:
      TZ: ${TIMEZONE}
      DEV_USER: ${DEV_USER}
    working_dir: /home/${DEV_USER}
    volumes:
      - ${HOST_HOME_DIR}/${DEV_DIR}:/home/${DEV_USER}
      - ${HOST_HOME_DIR}/${ADDITIONAL_DIR}:/home/${DEV_USER}/${ADDITIONAL_DIR}
      - ${HOST_HOME_DIR}/${DEV_DIR}/${SITES_DIR}:/sites
      - ${HOST_HOME_DIR}/${DEV_DIR}/${APP_DIR}:/core
      - ${DOCKER_SOCK_FILE}:${DOCKER_SOCK_FILE}
      - ruby:/usr/local/ruby
      - node:/usr/local/node
      - php-fpm:/usr/local/php
      - python2:/usr/local/python2
      - python3:/usr/local/python3
    ports:
      - "60001:60001"
      - "3000:3000"
      - "25:25"
    links:
      - ruby
      - node
      - mysql
      - redis
      - php-fpm
      - nginx
      - python2
      - python3
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
    container_name: rabbitmq
  redis:
    image: redis:4.0.2-alpine
    ports:
      - "6372:6379"
    container_name: redis
  nginx:
    image: micalexander/alpine-nginx-1.13.7:latest
    environment:
      FASTCGI_PASS: php-fpm
    deploy:
      replicas: 3
    container_name: nginx
    restart: always
    volumes:
      - ${HOST_HOME_DIR}/${DEV_DIR}/${SITES_DIR}:/sites
      - ${HOST_HOME_DIR}/${DEV_DIR}/${APP_DIR}:/core
    ports:
      - "8080:8080"
      - "4443:443"
    expose:
      - "8080"
    links:
      - php-fpm
  mysql:
    image: mariadb:10.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mysql
    restart: always
    volumes:
      - ${HOST_HOME_DIR}/${DEV_DIR}/${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${HOST_HOME_DIR}/${DEV_DIR}/${MYSQL_CNF}:/etc/mysql/conf.d
  php-fpm:
    image: micalexander/alpine-php-fpm-7.2.11
    ports:
      - "9000:9000"
    environment:
      TZ: ${TIMEZONE}
    container_name: php-fpm
    restart: always
    volumes:
      - ${HOST_HOME_DIR}/${DEV_DIR}/${SITES_DIR}:/sites
      - ${HOST_HOME_DIR}/${DEV_DIR}/${APP_DIR}:/core
      - php-fpm:/usr/local/php
  python2:
    image: micalexander/alpine-python-2.7.13:latest
    container_name: python2
    restart: always
    command: tail -f /dev/null
    volumes:
      - python2:/usr/local/python2
  python3:
    image: micalexander/alpine-python-3.6.1:latest
    container_name: python3
    restart: always
    command: tail -f /dev/null
    volumes:
      - python3:/usr/local/python3
  ruby:
    image: micalexander/alpine-ruby-2.4.1:latest
    container_name: ruby
    restart: always
    command: tail -f /dev/null
    volumes:
      - ruby:/usr/local/ruby
  node:
    image: micalexander/alpine-node-8.12:latest
    container_name: node
    restart: always
    command: tail -f /dev/null
    volumes:
      - node:/usr/local/node
volumes:
  ruby:
  node:
  mysql:
  php-fpm:
  python2:
  python3:
